---
repos:
  # golang pre commits
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: golangci-lint
      # - id: go-unit-tests  # skipped because no unit tests
      - id: go-generate
      - id: go-build
      - id: go-mod-tidy

  # tf lint & fmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        exclude: '^examples/.*$'
